// Generated by CoffeeScript 1.6.3
(function() {
  var HackApiClient;

  HackApiClient = require('./index.coffee');

  module.exports = function(username, password) {
    var orirequest, robot;
    robot = new HackApiClient;
    orirequest = robot._request;
    rotbot._request = function(url, opts, cb) {
      var _this = this;
      return orirequest.call(this, url, opts, function(err, body, res) {
        if (xxxxx) {
          _this.login(username, password, '', function(err) {
            if (err) {
              cb && cb(err);
            } else {
              return orirequest(url, opts, cb);
            }
          });
          return;
        }
        return cb && cb.call(_this, err, body, res);
      });
    };
    return robot;
  };

}).call(this);

/*
//@ sourceMappingURL=robot.map
*/
